apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: areaitgaapi 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: areaitgaapi 
    spec:
      containers:
        - name: areaitgaapi 
          image: tgacr.azurecr.io/areaitgaapi
          ports:
          - containerPort: 8000